# Generated by Django 5.2.12 on 2026-04-12 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.FloatField(null=True)),
                ('Order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform_name', models.CharField(max_length=200, null=True)),
                ('Website_link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Category_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_to_category', to='cart.category'),
        ),
        migrations.CreateModel(
            name='Product_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(null=True)),
                ('Original_price', models.FloatField(null=True)),
                ('Rating', models.FloatField(null=True)),
                ('Reviews_count', models.IntegerField(null=True)),
                ('Stock_status', models.CharField(max_length=200, null=True)),
                ('Delivery_time', models.CharField(max_length=200, null=True)),
                ('Product_link', models.CharField(max_length=300, null=True)),
                ('list_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_to_platform', to='cart.platform')),
                ('list_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_to_product', to='cart.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_to_listing', to='cart.product_listing')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('ord_item_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_to_order', to='cart.orders')),
                ('ord_item_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_to_listing', to='cart.product_listing')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('cart_item_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_to_cart', to='cart.cart')),
                ('cart_item_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_to_listing', to='cart.product_listing')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=200, null=True)),
                ('Registration_date', models.DateField(auto_now_add=True, null=True)),
                ('Phone', models.CharField(max_length=15, null=True)),
                ('Budget', models.FloatField(null=True)),
                ('Address', models.TextField(null=True)),
                ('User_role', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='order_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_to_user', to='cart.registration'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('noti_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_product', to='cart.product')),
                ('noti_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_to_user', to='cart.registration')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_to_user', to='cart.registration'),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_to_admin', to='cart.registration'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(null=True)),
                ('Review_text', models.TextField(null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('rev_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_to_product', to='cart.product')),
                ('rev_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_to_user', to='cart.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Search_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('search_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_to_user', to='cart.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target_price', models.FloatField(null=True)),
                ('Added_date', models.DateTimeField(auto_now_add=True)),
                ('watch_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_to_product', to='cart.product')),
                ('watch_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_to_user', to='cart.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
