# Generated by Django 5.2.12 on 2026-04-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orders_platform_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='noti_pro',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='noti_reg',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='ord_item_listing',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='ord_item_order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_reg',
        ),
        migrations.RemoveField(
            model_name='product_listing',
            name='list_platform',
        ),
        migrations.RemoveField(
            model_name='price_history',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='product_listing',
            name='list_pro',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rev_pro',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rev_reg',
        ),
        migrations.RemoveField(
            model_name='search_history',
            name='search_reg',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_pro',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_reg',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Created_date',
            new_name='Added_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='Product_title',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_cat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_reg',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Password',
        ),
        migrations.AddField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.registration'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('not_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Total_amount', models.FloatField(null=True)),
                ('Payment_status', models.CharField(max_length=200, null=True)),
                ('Order_status', models.CharField(max_length=200, null=True)),
                ('order_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('ord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Payment_amount', models.FloatField(null=True)),
                ('Payment_method', models.CharField(max_length=200, null=True)),
                ('pay_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(null=True)),
                ('Review_text', models.TextField(null=True)),
                ('Review_date', models.DateField(auto_now_add=True, null=True)),
                ('rev_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('rev_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('wish_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart_items',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Price_history',
        ),
        migrations.DeleteModel(
            name='Product_listing',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Search_history',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
