# Generated by Django 5.2.12 on 2026-04-13 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_notifications_noti_pro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='ord',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rev_reg',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wish_reg',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_reg',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='not_reg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_reg',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rev_prod',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wish_prod',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Added_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_prod',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_stock',
        ),
        migrations.AddField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('preferred_category', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Order_details',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
