# Generated by Django 5.2.12 on 2026-04-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
