# Generated by Django 5.2.12 on 2026-04-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Password',
            new_name='password',
        ),
    ]
