# Generated by Django 5.2.12 on 2026-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='common_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
