# Generated by Django 5.2.12 on 2026-04-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_product_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='common_name',
        ),
    ]
