# Generated by Django 5.2.12 on 2026-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_agentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
