# Generated by Django 5.2.12 on 2026-04-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_cart_is_agent_order_is_simulated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_agent',
        ),
    ]
