# Generated by Django 5.2.12 on 2026-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cart_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='decision',
            field=models.CharField(choices=[('BUY', 'BUY'), ('WAIT', 'WAIT'), ('SKIP', 'SKIP')], max_length=10),
        ),
    ]
