# Generated by Django 5.2.12 on 2026-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_userprofile_card_name_userprofile_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
