# Generated by Django 5.2.12 on 2026-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_product_ai_recommendation_product_ai_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_recommendation',
            field=models.CharField(blank=True, default='Wait', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ai_score',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
