# Generated by Django 5.2.14 on 2026-05-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_order_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='platform',
            field=models.CharField(blank=True, choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart')], max_length=20, null=True),
        ),
    ]
