# Generated by Django 5.2.14 on 2026-06-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_remove_product_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
    ]
