from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home1'),
    path('login/', views.login, name='login'),


    # 🔐 Password Reset Flow
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('logout/', views.logout, name='logout'),
    path('admin_register/', views.admin_register, name='admin_register'),
    path('user_register/', views.user_register, name='user_register'),
    path('user_login/', views.user_login, name='user_login'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('category/<int:id>/', views.products_by_category, name='products_by_category'),
    path('products/', views.products, name='products'),
    path('product-image/<int:product_id>/', views.product_image_proxy, name='product_image_proxy'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_page, name='cart_page'),
    path('increase/<int:id>/', views.increase_qty, name='increase_qty'),
    path('decrease/<int:id>/', views.decrease_qty, name='decrease_qty'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('remove-from-cart/<int:id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order-success/', views.order_success, name='order_success'),
    path('orders/', views.orders, name='orders'),
    path('cancel-order/<int:id>/', views.cancel_order, name='cancel_order'),
    path('invoice/<int:id>/', views.invoice, name='invoice'),
    path('buy-now/<int:id>/', views.buy_now, name='buy_now'),
    path('wishlist/', views.wishlist_page, name='wishlist'),
    path('wishlist/add/<int:id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('profile/', views.profile, name='profile'),
    path('admin_products/', views.admin_products, name='admin_products'),
    path('products/delete/<int:id>/', views.delete_product, name='delete_product'),
    path('products/edit/<int:id>/', views.edit_product, name='edit_product'),
    path('admin_categories/', views.admin_categories, name='admin_categories'),
    path('admin_users/', views.admin_users, name='admin_users'),
    path('admin_orders/', views.admin_orders, name='admin_orders'),
    path('orders/update/<int:id>/', views.update_order_status, name='update_order_status'),
    path('admin_reviews/', views.admin_reviews, name='admin_reviews'),
    path('users/delete/<int:id>/', views.delete_user, name='delete_user'),
    path('add_product/', views.add_product, name='add_product'),
    path('notifications/', views.notifications_page, name='notifications'),
    path('notifications/read/<int:id>/', views.mark_as_read, name='mark_as_read'),
    path('notifications/read-all/',views.mark_all_as_read,name='mark_all_as_read'),
    path('price-graph/<int:id>/', views.price_graph, name='price_graph'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('compare/', views.compare_products, name='compare_products'),
    path('ai-simulation/', views.ai_simulation, name='ai_simulation'),
    path('ai-price_predict/', views.price_predict, name='price_predict'),
    path('run-agent/', views.run_agent, name='run_agent'),
    path('agent-logs/', views.agent_logs, name='agent_logs'),
    path('settings/', views.settings_page, name='settings'),
    path('test-email/', views.test_email, name='test_email'),
    path('my-reviews/', views.user_reviews, name='user_reviews'),
    path('api/product-search/', views.product_search_ajax, name='product_search_ajax'),
    path('activity/', views.user_activity_log, name='user_activity'),
    path('add-payment/', views.add_payment, name='add_payment'),
    path('chatbot/', views.chatbot_page, name='chatbot'),
]
